// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
// See the LICENCE file in the repository root for full licence text.

using NUnit.Framework;
using osu.Game.Beatmaps;
using osu.Game.Rulesets.Difficulty;
using osu.Game.Rulesets.Mania.Difficulty;
using osu.Game.Rulesets.Mania.Mods;
using osu.Game.Tests.Beatmaps;

namespace osu.Game.Rulesets.Mania.Tests
{
    public class ManiaDifficultyCalculatorTest : DifficultyCalculatorTest
    {
        protected override string ResourceAssembly => "osu.Game.Rulesets.Mania.Tests";

        [TestCase(2.3028148997803708d, 242, "diffcalc-test")]
        public void Test(double expectedStarRating, int expectedMaxCombo, string name)
            => base.Test(expectedStarRating, expectedMaxCombo, name);

        [TestCase(2.8495334099236853d, 242, "diffcalc-test")]
        public void TestClockRateAdjusted(double expectedStarRating, int expectedMaxCombo, string name)
            => Test(expectedStarRating, expectedMaxCombo, name, new ManiaModDoubleTime());

        [TestCase(6.3028d, 6050, @"everything.Aoi - King Atlantis (WinterIsDead_old) [New World]")]
        [TestCase(9.5469d, 11082, @"everything.Aoi - King Atlantis (_Kobii) [Abyssal Overlord]")]
        [TestCase(8.029d, 4870, @"everything.B.U.S feat. MAKI - promise (MEIDAN) [Extreme]")]
        [TestCase(7.5109d, 4222, @"everything.BilliumMoto - LIGHT LEFT BEHIND (-mint-) [AND IN THE DARKNESS BIND THEM]")]
        [TestCase(6.7934d, 3889, @"everything.BilliumMoto - LIGHT LEFT BEHIND (-mint-) [ULTRA]")]
        [TestCase(7.6694d, 8495, @"everything.BlackY vs. Yooh - HAVOX (Camellia's XATAXLYSM Remix) (Ryax) [TOTAL XOLLAPSE]")]
        [TestCase(6.627d, 2018, @"everything.CROOVE - Aquaris (AirAqua) [Wanderer x1.1]")]
        [TestCase(7.1955d, 2018, @"everything.CROOVE - Aquaris (AirAqua) [Wanderer x1.2]")]
        [TestCase(7.809d, 2018, @"everything.CROOVE - Aquaris (AirAqua) [Wanderer x1.3]")]
        [TestCase(8.2681d, 2018, @"everything.CROOVE - Aquaris (AirAqua) [Wanderer x1.4]")]
        [TestCase(6.0293d, 2018, @"everything.CROOVE - Aquaris (AirAqua) [Wanderer]")]
        [TestCase(6.38d, 6714, @"everything.Camellia - Electromagnetic Stealth Girl Born In Philadelphia (Ryax) [Disappearance of the USS Eldridge]")]
        [TestCase(5.3304d, 2907, @"everything.Camellia - Fastest Crash (inteliser) [cracked]")]
        [TestCase(6.5748d, 8139, @"everything.Camellia - Flamewall (riunosk) [Incineration]")]
        [TestCase(10.0d, 9837, @"everything.Camellia - K.Y.A.F.A. (Evening) [ETERNAL HAVOC +]")]
        [TestCase(9.2832d, 9639, @"everything.Camellia - K.Y.A.F.A. (Evening) [ETERNAL HAVOC]")]
        [TestCase(8.6168d, 9005, @"everything.Camellia - K.Y.A.F.A. (Evening) [GEKIDO'S ENDLESS RAMPAGE]")]
        [TestCase(6.9492d, 6778, @"everything.Camellia - K.Y.A.F.A. (Evening) [RELENTLESS MASSACRE]")]
        [TestCase(6.5585d, 6278, @"everything.Camellia - K.Y.A.F.A. (Evening) [UNSTOPPABLE DOMINATION]")]
        [TestCase(10.0d, 12846, @"everything.Camellia - Kikai No Tsubasa (feat. Kasane Teto) (Ycloki) [Celtic Gearheart  Ascension]")]
        [TestCase(8.0903d, 5761, @"everything.Camellia - NEURO-CLOUD-9 (Ska) [099]")]
        [TestCase(6.8237d, 7976, @"everything.Camellia - OOPARTS (-mint-) [Antikythera]")]
        [TestCase(7.3895d, 9958, @"everything.Camellia - OOPARTS (AWMRone) [OOccultism]")]
        [TestCase(7.9979d, 11252, @"everything.Camellia - Parallel Universe Shifter (-mint-) [Quantum Field Disruption]")]
        [TestCase(8.042d, 3789, @"everything.Camellia - S.A.T.E.L.L.I.T.E. (Cut Ver.) (ade_maine) [Celestial]")]
        [TestCase(6.6028d, 6830, @"everything.Camellia - We Could Get More Machinegun Psystyle! (And More Genre Switches) (Rio1-) [Relentless]")]
        [TestCase(8.0725d, 7970, @"everything.Camellia feat. Nanahira - finorza (YuzakiTsukasa) [Questa e la fine]")]
        [TestCase(8.912d, 7161, @"everything.Chinoi - Kyu-kurarin (ruka) [rukarin]")]
        [TestCase(7.2975d, 9817, @"everything.D-D-Dice vs. siromaru - Catch the Glory (Rocma) [Dignity]")]
        [TestCase(7.8916d, 3412, @"everything.DETRO - volcanic ([Crz]Player) [Challenge]")]
        [TestCase(8.1d, 9689, @"everything.DETRO - volcanic (_underjoy) [Pyroclasm]")]
        [TestCase(5.8609d, 1460, @"everything.DEVNULL - Rave 7 (hi19hi19) [Hard]")]
        [TestCase(8.0701d, 1656, @"everything.DEVNULL - Rave 7 (hi19hi19) [Insane]")]
        [TestCase(5.1592d, 4015, @"everything.DJ SHARPNEL - FAKE PROMISE (Shoegazer) [Eternity]")]
        [TestCase(5.5539d, 4285, @"everything.DJ Sharpnel - Aim Burst (HikariNayo) [IcyWorld's Challenge Lv.10]")]
        [TestCase(5.4358d, 5165, @"everything.DJ Sharpnel - Cyber Inductance (Speed Up Ver.) (IcyWorld) [NB4]")]
        [TestCase(7.9955d, 16070, @"everything.DeformedEutopia (Nirotiy + AiSS) - Chong Xiao - The Multitude of Empyrean - (Ycloki) [Millennial Supersession]")]
        [TestCase(6.882d, 11234, @"everything.DeltaH, Gardens, glasse, Musature, Myntian, Sad Keyboard Guy - Rite of Ascendancy (FLeVI) [After Ragnarok  4K]")]
        [TestCase(9.172d, 18400, @"everything.DeltaH, Gardens, glasse, Musature, Myntian, Sad Keyboard Guy - Rite of Ascendancy (FLeVI) [Ultimate Evolution  tyrcs' 7K]")]
        [TestCase(6.177d, 2488, @"everything.E-Type - Here I Go Again (Jole) [where u going though 1.2x]")]
        [TestCase(8.2473d, 5038, @"everything.Feryquitous - Descent ([-Roxas-]) [Caliginem]")]
        [TestCase(7.9712d, 4471, @"everything.Filthy - You can't escape from the mission (DannyPX) [Oscillation]")]
        [TestCase(7.1927d, 8944, @"everything.Frums - HALL (guden) [NULL]")]
        [TestCase(9.3709d, 4857, @"everything.Fvrwvrd - Speedcore Sonata (Critical_Star) [Incessant Rain]")]
        [TestCase(7.7452d, 1917, @"everything.HAARPER - DROP IT LIKE IT'S HOT!!! ([LS]chilling) [Prosaic's Challenge x1.1_P]")]
        [TestCase(8.4139d, 1917, @"everything.HAARPER - DROP IT LIKE IT'S HOT!!! ([LS]chilling) [Prosaic's Challenge x1.2_P]")]
        [TestCase(9.0392d, 1917, @"everything.HAARPER - DROP IT LIKE IT'S HOT!!! ([LS]chilling) [Prosaic's Challenge x1.3_P]")]
        [TestCase(9.5699d, 1917, @"everything.HAARPER - DROP IT LIKE IT'S HOT!!! ([LS]chilling) [Prosaic's Challenge x1.4_P]")]
        [TestCase(6.7744d, 1917, @"everything.HAARPER - DROP IT LIKE IT'S HOT!!! ([LS]chilling) [Prosaic's Challenge]")]
        [TestCase(7.687d, 4069, @"everything.HOT PLACE - TMI (ade_maine) [Too Much Anchor]")]
        [TestCase(6.5897d, 7647, @"everything.Halv vs. kuro - Evreka (kilotek) [Khrysos]")]
        [TestCase(8.379d, 5362, @"everything.Hatsuki Yura - Snow Veil (HikariNayo) [LTD's Veil]")]
        [TestCase(5.7067d, 4722, @"everything.Hinatabi Bitter Sweets - Hana no Yakusoku (SurfChu85) [a blooming promise]")]
        [TestCase(9.578d, 4022, @"everything.Hoshimachi Suisei - BIBBIDIBA (Starmination FULLCORE Bootleg) (Shirasu_09) [Omega Pattern Practice]")]
        [TestCase(9.7048d, 15974, @"everything.HyuN feat. Sennzai - Duplicity Shade (_underjoy) [Metamorphosis]")]
        [TestCase(5.7d, 2358, @"everything.Junk - Life is PIANO (yahweh) [Extra]")]
        [TestCase(6.7d, 2481, @"everything.Junk - Life is PIANO (yahweh) [LIFE]")]
        [TestCase(6.6794d, 5090, @"everything.Kabocha feat. Aitsuki Nakuru - Dear The Night I Loved (-mint-) [A Painting Forever Unfinished]")]
        [TestCase(6.1127d, 2846, @"everything.Kobaryo - Cross The Finish Line [feat. Nanahira] (Rhezie) [Extra]")]
        [TestCase(8.6355d, 8395, @"everything.KopophobiA & Spacechimp - No time to die (DannyPX) [Life Flashes]")]
        [TestCase(6.1648d, 7128, @"everything.Kurokotei - Galaxy Collapse (Mat) [Cataclysmic Hypernova]")]
        [TestCase(7.0664d, 8883, @"everything.Kurokotei - Scattered Faith (4hri) [Catastrophic Trust]")]
        [TestCase(8.2148d, 10215, @"everything.Kyutatsuki - Dimension Wars (gzdongsheng) [Ragnarok]")]
        [TestCase(12.0d, 13022, @"everything.Kyutatsuki - Sea of Stars (tyrcs) [Interstellar Expedition]")]
        [TestCase(8.761d, 9142, @"everything.Laur - SYSTEM ERROR (Leeju) [Obsession Nyctophilia]")]
        [TestCase(7.3869d, 4016, @"everything.Lime - BEYOND (FLeVI) [LN Aurora Australis]")]
        [TestCase(10.6803d, 4711, @"everything.Lime - BEYOND (tyrcs) [Ascension]")]
        [TestCase(8.8177d, 3580, @"everything.Lime - Campanella (BKwind) [Lv.22  Eternal]")]
        [TestCase(8.1685d, 4487, @"everything.Ludicin - Bismuth (ababa) [Archaic's Supernova]")]
        [TestCase(8.7374d, 4873, @"everything.Ludicin - Bismuth (ababa) [Singularity]")]
        [TestCase(8.8118d, 12458, @"everything.Ludicin - Echoes of Memoria (U1d) [Preinfinitism]")]
        [TestCase(10.152d, 14827, @"everything.Ludicin - Echoes of Memoria (tyrcs) [Fragments of Reality]")]
        [TestCase(10.346d, 17713, @"everything.Ludicin - Everlasting Eternity (Critical_Star) [Endless Solo of Solitude]")]
        [TestCase(7.0261d, 8444, @"everything.Ludicin - Everlasting Eternity (NacFuwu) [Spacial Perpetuity]")]
        [TestCase(8.009d, 10245, @"everything.Ludicin - Everlasting Eternity (uL-) [Majestic Presence]")]
        [TestCase(7.6023d, 10861, @"everything.Ludicin - Fallen Symphony (riunosk) [Incomprehensible Musicality]")]
        [TestCase(8.158d, 15203, @"everything.Ludicin - Lost Requiem (chy030_ft_pH5_6) [Lazarus Resurgam]")]
        [TestCase(8.6149d, 4628, @"everything.Ludicin - Onus Regulus (uL-) [Conqueror Of The Universe  4K Extreme]")]
        [TestCase(10.696d, 6618, @"everything.Ludicin - Onus Regulus (uL-) [Fated Battle  Blocko's 7K Ultimate]")]
        [TestCase(7.4241d, 3971, @"everything.Ludicin - Onus Regulus (uL-) [Judgmental Obliteration  4K Extra]")]
        [TestCase(6.6822d, 2995, @"everything.Ludicin - Signal (kartofle) [Usagi's Intangible Connection]")]
        [TestCase(8.5759d, 6614, @"everything.Manowar - The Last Winged Unicorn (Night Bunny 7) [Mina's Novice Lv.82 1.1x]")]
        [TestCase(9.3071d, 6495, @"everything.Manowar - The Last Winged Unicorn (Night Bunny 7) [Mina's Novice Lv.82 1.2x]")]
        [TestCase(9.9413d, 6427, @"everything.Manowar - The Last Winged Unicorn (Night Bunny 7) [Mina's Novice Lv.82 1.3x]")]
        [TestCase(10.5021d, 6383, @"everything.Manowar - The Last Winged Unicorn (Night Bunny 7) [Mina's Novice Lv.82 1.4x]")]
        [TestCase(7.6998d, 6704, @"everything.Manowar - The Last Winged Unicorn (Night Bunny 7) [Mina's Novice Lv.82]")]
        [TestCase(5.4731d, 2163, @"everything.Matt - Friday Night Funkin' Vs Matt Mod (SeanJhersen) [Sporting]")]
        [TestCase(7.878d, 4552, @"everything.Meramipop feat. Studio Syrup Comfiture - Zillion Lights (HikariNayo) [One Zillion Chordjacks]")]
        [TestCase(5.512d, 5031, @"everything.Mitsukiyo - Gregorius  Symphony (Critical_Star) [Extreme]")]
        [TestCase(7.572d, 7159, @"everything.Mitsukiyo - Gregorius  Symphony (Critical_Star) [Salvation for All]")]
        [TestCase(7.013d, 6291, @"everything.Mitsukiyo - Gregorius  Symphony (Critical_Star) [Torment]")]
        [TestCase(5.7d, 2247, @"everything.Mrs. GREEN APPLE - Ao to Natsu (katagiri Bootleg) (Sped Up & Cut Ver.) (frawog) [Summer Memories]")]
        [TestCase(10.2d, 6378, @"everything.Mrs. GREEN APPLE - StaRt (Liker) [New beginnings]")]
        [TestCase(8.9d, 6378, @"everything.Mrs. GREEN APPLE - StaRt (Liker) [x0.85]")]
        [TestCase(4.3718d, 872, @"everything.NIKO - Maid of Fire (Furry) [Jackhammer Madness]")]
        [TestCase(5.5d, 2321, @"everything.Neko Hacker - Circulation (Critical_Star) [Ohayo~]")]
        [TestCase(7.3837d, 7264, @"everything.Noah - Deadly force - Put an end (riunosk) [Immeasurable Momentum]")]
        [TestCase(8.3579d, 24813, @"everything.Noah feat. Ai Ohsera - Rebirth the end (Begin) [Denouement]")]
        [TestCase(8.1152d, 8615, @"everything.Normal1zer vs. Broken Nerdz - Cybernetic Mastermind No.7 (BKwind) [LazorBeamZ]")]
        [TestCase(4.73d, 3634, @"everything.One-T + Cool-T - The Magic Key (jasionnn) [1.0x]")]
        [TestCase(7.712d, 6723, @"everything.Park Mi Kyung - Eve's Warning (ChinaSpyBalloon) [[1.0x] popomon NOLN]")]
        [TestCase(6.8269d, 7107, @"everything.ReeK - Multigenre Smackdown (-mint-) [Vine Boom Sound Effect (bass boosted)]")]
        [TestCase(7.6503d, 3247, @"everything.S.S.H. - Intersect Thunderbolt-Remix (ljqandylee) [7K Exceed]")]
        [TestCase(4.5d, 2154, @"everything.SP-# - tinnitus (taba2) [Hyper]")]
        [TestCase(8.5d, 4188, @"everything.SP-# - tinnitus (taba2) [Other]")]
        [TestCase(7.0798d, 8265, @"everything.SUPER MWC KART - Purple Palace (-mint-) [Rainbow Road Revolution]")]
        [TestCase(9.0d, 17579, @"everything.Sayuri x MY FIRST STORY - Reimei (ExNeko) [Foredawn.]")]
        [TestCase(5.57d, 1932, @"everything.Seiryu - BLUE DRAGON (ExUsagi) [Insanity]")]
        [TestCase(9.0312d, 9326, @"everything.Shade - Rebirth the edge (lemonguy) [Hyper Weapon]")]
        [TestCase(5.3d, 5891, @"everything.Sharlo - Xue Mao Jiao (Drum-Hitnormal) [CS' 7K Wo Shi Ni De Mao]")]
        [TestCase(8.6991d, 11723, @"everything.Silentroom vs. Frums - Aegleseeker ('Afterworld' Full Version) (eZmmR) [New Era Dimension]")]
        [TestCase(11.4694d, 2158, @"everything.SpaceChimp - Rebel Yell Rmx (WinterIsDead_old) [Jacks]")]
        [TestCase(7.545d, 1564, @"everything.SpaceChimp - Rebel Yell Rmx (WinterIsDead_old) [Streams]")]
        [TestCase(6.6638d, 2820, @"everything.Sta - The Ricochet (gogozzzx) [Extreme]")]
        [TestCase(7.864d, 5781, @"everything.Stellabee - The Fastest Love Song (Edit Ver.) (Mich_) [3]")]
        [TestCase(5.4229d, 4478, @"everything.Stereoman & Yunomi - Cinderella Baby (feat. Antenna Girl) (KOTONOHOUSE remix) (YuEast 2018) [Fulfillment of Dreams (w Hidden)]")]
        [TestCase(8.1617d, 2733, @"everything.StudioEIM - Crescent Moon Island (Shoegazer) [Kuro 1.05x (181bpm)]")]
        [TestCase(8.8061d, 8170, @"everything.Synestia, Disembodied Tyrant - The Poetic Edda (feat. Ben Duerr) (kilotek) [Sigrdrifumal  Kilotek vs. Domajnyk Pear]")]
        [TestCase(4.6075d, 4729, @"everything.Team Grimoire - C18H27NO3(extend) ([Shana Lesus]) [4K Capsaicin]")]
        [TestCase(9.2347d, 4808, @"everything.The Quick Brown Fox - Burning Brain (DannyPX) [Challenge]")]
        [TestCase(7.9754d, 10015, @"everything.Toby Fox - Rude Buster (Camellia Remix) (BKwind) [Don't Forget]")]
        [TestCase(11.0869d, 13662, @"everything.Toby Fox - Rude Buster (Camellia Remix) (aci) [We are Forever Friends]")]
        [TestCase(6.8369d, 4965, @"everything.TryHardNinja - Revenge (feat. CaptainSparklez) (ReeK's Dude, What's A Genre Remix) (-mint-) [Creeper]")]
        [TestCase(7.7557d, 6969, @"everything.UNDEAD CORPORATION - MEGALOMANIA ([-Omni-]) [LOCKED INSIDE DARKNESS]")]
        [TestCase(7.057d, 2768, @"everything.UNDEAD CORPORATION - The Empress scream off ver (TheZiemniax) [Jepetski's Empress]")]
        [TestCase(5.2023d, 5834, @"everything.USAO & Kobaryo - WACCA ULTRA DREAM MEGAMIX (ler1211) [FANTASY]")]
        [TestCase(5.892d, 3525, @"everything.Ueda reina - Literature (Darkbbt) [MongolCJ's Challenge]")]
        [TestCase(6.8d, 1683, @"everything.Unlike Pluto feat. Mike Taylor - EVERYTHING BLACK feat. RATIRL [Lieless FRENCHCORE BOOTLEG] (Sped Up & Cut Ver.) (Chappell Roan) [EDGY DIFFNAME]")]
        [TestCase(6.7795d, 750, @"everything.Unlucky Morpheus - Wer ist Faust (Carpihat) [Wie geht es Faust]")]
        [TestCase(5.5942d, 1581, @"everything.V.A. - 6k Advanced Pack Vol.C6 (_IceRain) [dj TAKA - Quaver [16]]")]
        [TestCase(5.53d, 2623, @"everything.V.A. - untitled chordjack pack (- Ran Mitake -) [Cuco - Melting]")]
        [TestCase(9.336d, 3307, @"everything.Various Artist - Super Hard Jack Challenge ([Crz]Rachel) [Nekomata Master feat. Shimotsuki Haruka - Element of SPADA (Omega Ver.)]")]
        [TestCase(7.9592d, 16027, @"everything.Various Artists - 4K LN Dan Courses v2 - FINAL - (_underjoy) [14th Dan - Yami (Marathon)]")]
        [TestCase(8.3378d, 21054, @"everything.Various Artists - 4K LN Dan Courses v2 - FINAL - (_underjoy) [15th Dan - Yume (Marathon)]")]
        [TestCase(8.549d, 10562, @"everything.Various Artists - Dan ~ REFORM ~ 2nd Pack (DDMythical) [~ EXTRA-DELTA ~ (Marathon)]")]
        [TestCase(9.3171d, 9749, @"everything.Various Artists - Dan ~ REFORM ~ 2nd Pack (DDMythical) [~ EXTRA-EPSILON ~ (Marathon)]")]
        [TestCase(11.0d, 15548, @"everything.Various Artists - Dan ~ REFORM ~ FINAL ([GB]Thaumiel) [~ FINAL - ETA ~ ( Marathon )]")]
        [TestCase(8.024d, 7590, @"everything.Various Artists - LTD Pack (LTD) [Hatsuki Yura - Onyx Veil]")]
        [TestCase(10.0101d, 11654, @"everything.Various Artists - Zeta Sample Dan v2 (Brunliko) [~ EXTRA-ZETA ~ (Marathon) (real chart) (credit to emik)]")]
        [TestCase(6.6925d, 4681, @"everything.Yuyoyuppe - AiAe (Fullerene-) [Wafles' SHD]")]
        [TestCase(5.1475d, 2050, @"everything.Zekk - Re_Construct (Lita-) [Re_Sign]")]
        [TestCase(7.8736d, 7276, @"everything.aa...hisuichazuke... - steganography (-mint-) [Cipher Encryption]")]
        [TestCase(7.614d, 3005, @"everything.aespa - Live My Life (Jhown) [You & Me...]")]
        [TestCase(7.108d, 3333, @"everything.anubasu-anubasu - Materialize Anything (-NoName-) [Jinjin's Synthesis]")]
        [TestCase(7.5458d, 5452, @"everything.beatMARIO - Saishuu Kichiku Imouto Flandre-S (Camellia's Remix) (-mint-) [Calamity at the Scarlet Mansion]")]
        [TestCase(6.6726d, 2357, @"everything.cosMo@BousouP - Deux Saint-Co odyssey!! (lemonguy) [EXCEED]")]
        [TestCase(7.336d, 2829, @"everything.fripside - Hesitation Snow (shimizu778) [ok]")]
        [TestCase(7.3958d, 1340, @"everything.goreshit - daddy can change (icouldentthink) [men]")]
        [TestCase(7.8005d, 9937, @"everything.kanemiko & Kyutatsuki & Aoi - Fractal Vertex (-mint-) [Cosmic Intersection]")]
        [TestCase(7.862d, 7974, @"everything.katagiri - Kyuukou (BKwind) [Hyperflow]")]
        [TestCase(7.954d, 3774, @"everything.lexycat - #cherryCrush (Hal0y) [Awaaa]")]
        [TestCase(6.623d, 3027, @"everything.lia - farewell song (shimizu778) [ok]")]
        [TestCase(6.9883d, 8265, @"everything.one eight - N (Archaic84) [Ascend]")]
        [TestCase(6.9766d, 8391, @"everything.one eight - N (Archaic84) [_uj's Reflection]")]
        [TestCase(10.2459d, 6932, @"everything.penoreri - Lancelot ~Flame of the Rebellion~ (_Kobii) [Stellium]")]
        [TestCase(7.611d, 6556, @"everything.rejection - White Canvas (feat. Aitsuki Nakuru) (Itawachi) [4K  Far in the White Sky (Full)]")]
        [TestCase(5.4563d, 5782, @"everything.sabi - true DJ MAG top ranker's song Zenpen (katagiri Remix) (FLeVI) [KEMOMIMI MANIA SQUAD]")]
        [TestCase(4.9402d, 3155, @"everything.t+pazolite - Party in the HOLLOWood feat. Nanahira (HOLLOWeen Sitchaka Metchaka Remix) (_Asha) [Party]")]
        [TestCase(3.2271d, 260, @"everything.thrxll - Trill Practice (thrxll) [150 BPM]")]
        [TestCase(6.717d, 3953, @"everything.typeMARS - Triumph & Regret ([ A v a l o n ]) [Regret 1.5x (262bpm) OD8.5]")]
        [TestCase(4.6407d, 3994, @"everything.typeMARS - Triumph & Regret ([ A v a l o n ]) [Regret]")]
        [TestCase(7.211d, 2784, @"everything.winddrums - Goddess Bless you (Shima Rin) [Ash's HEAVENLY]")]
        [TestCase(7.1787d, 6413, @"everything.xi - XaleidoscopiX (cherrychou) [Re7sRef]")]
        [TestCase(6.3314d, 6165, @"everything.youman feat. GUMI - Weenywalker (-mint-) [Predetermination]")]

        public void TestEverything(double expectedStarRating, int expectedMaxCombo, string name)
            => base.Test(expectedStarRating, expectedMaxCombo, name);

        protected override DifficultyCalculator CreateDifficultyCalculator(IWorkingBeatmap beatmap) => new ManiaDifficultyCalculator(new ManiaRuleset().RulesetInfo, beatmap);

        protected override Ruleset CreateRuleset() => new ManiaRuleset();
    }
}
